title: Gabriel Adesina
logo: HeadShot.jpg
description: A data analyst with 2 years experience working with diffeent analytic tool using advance excel(VBA & MACRo) for report automation, ssis, SQL for data Manipulation & Interogation & Power BI to creating Intelligent Report .
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
