title: Gabriel Adesina
logo: HeadShot.jpg
description: A data analyst with 2 years of experience working with various analytic tools. Proficient in advanced Excel functions, VBA, and Macro automation for report automation, SSIS for Data integration and ETL processes, SQL for Data manipulation, querying, and database management and Power BI for creating intelligent Data visualization and dashboard reports.
theme: jekyll-theme-minimal
